CREATE TABLE IF NOT EXISTS analytics_snapshots (
  date TEXT PRIMARY KEY, -- YYYY-MM-DD
  total_views INTEGER NOT NULL DEFAULT 0,
  new_posts INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
